{% set name = "ftfy" %}
{% set version = "6.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ftfy-{{ version }}.tar.gz
  sha256: 9b3c3d90f84fb267fe64d375a07b7f8912d817cf86009ae134aa03e1819506ec

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  entry_points:
    - ftfy = ftfy.cli:main

requirements:
  host:
    - pip
    - python >=3.9
    - hatchling
  run:
    - python >=3.9
    - wcwidth

test:
  source_files:
    - tests
  imports:
    - ftfy
    - ftfy.bad_codecs
  commands:
    - pip check
    - ftfy --help
    - pytest -vvv --capture=tee-sys -k "not test_cli" tests
  requires:
    - pip
    - pytest

about:
  home: https://github.com/LuminosoInsight/python-ftfy/
  license: MIT
  license_file: LICENSE.txt
  summary: Fixes some problems with Unicode text after the fact
  doc_url: http://ftfy.readthedocs.io/

extra:
  recipe-maintainers:
    - rmax
    - FernandezMathieu
    - thewchan
