{% set name = "ftfy" %}
{% set version = "6.0.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9eb68533eb2a6124e96ed7f63049e6c519194fda3fae92629b5e0b5753cb2c8f

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  noarch: python
  entry_points:
    - ftfy = ftfy.cli:main

requirements:
  host:
    - python ==3.8.1
    - pip
  run:
    - python >=3.6,<3.9
    # Required for loading package data via `pkg_resources` module.
    - setuptools
    - wcwidth

test:
  requires:
    - pytest
  source_files:
    - tests
  commands:
    - py.test --deselect tests/test_cli.py  # [win]
    # CLI tests fail on windows.
    - py.test  # [not win]

about:
  home: https://github.com/LuminosoInsight/python-ftfy/
  license: MIT
  license_file: LICENSE.txt
  summary: Fixes some problems with Unicode text after the fact
  dev_url: https://github.com/LuminosoInsight/python-ftfy
  doc_url: http://ftfy.readthedocs.io/

extra:
  recipe-maintainers:
    - rmax
    - FernandezMathieu
