{% set name = "ftfy" %}
{% set version = "6.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ftfy-{{ version }}.tar.gz
  sha256: 693274aead811cff24c1e8784165aa755cd2f6e442a5ec535c7d697f6422a422

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  entry_points:
    - ftfy = ftfy.cli:main

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.7,<4.0
  run:
    - python >=3.7,<4.0
    - wcwidth >=0.2.5

test:
  source_files:
    - tests
  imports:
    - ftfy
    - ftfy.bad_codecs
  commands:
    - pip check
    - ftfy --help
    - pytest -vvv --capture=tee-sys -k "not test_cli" tests
  requires:
    - pip
    - pytest

about:
  home: https://github.com/LuminosoInsight/python-ftfy/
  license: MIT
  license_file: LICENSE.txt
  summary: Fixes some problems with Unicode text after the fact
  doc_url: http://ftfy.readthedocs.io/

extra:
  recipe-maintainers:
    - rmax
    - FernandezMathieu
    - thewchan
